'use client';

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Invoice, formatCurrency } from '@/types';

export function generatePDF(invoice: Invoice): Blob {
  const doc = new jsPDF();

  if (invoice.template === 'modern') {
    generateModern(doc, invoice);
  } else if (invoice.template === 'classic') {
    generateClassic(doc, invoice);
  } else {
    generateMinimal(doc, invoice);
  }

  return doc.output('blob');
}

function generateModern(doc: jsPDF, invoice: Invoice) {
  // Header gradient-ish band
  doc.setFillColor(59, 130, 246);
  doc.rect(0, 0, 210, 40, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('INVOICE', 15, 25);

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`#${invoice.number}`, 15, 32);

  doc.setFontSize(10);
  doc.text(`Date: ${invoice.date}`, 160, 20);
  doc.text(`Due: ${invoice.dueDate}`, 160, 26);

  // From / To
  let y = 55;
  doc.setTextColor(31, 41, 55);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('From:', 15, y);
  if (invoice.from.logo) {
    try { doc.addImage(invoice.from.logo, 'JPEG', 15, y + 2, 20, 20); } catch {}
  }
  doc.setFont('helvetica', 'normal');
  doc.text(invoice.from.name || 'Your Company', 15, y + 10);
  doc.text(invoice.from.email, 15, y + 15);
  doc.text(invoice.from.phone, 15, y + 20);
  doc.text(invoice.from.address, 15, y + 25);

  doc.setFont('helvetica', 'bold');
  doc.text('Bill To:', 110, y);
  doc.setFont('helvetica', 'normal');
  doc.text(invoice.to.name || 'Client Name', 110, y + 10);
  doc.text(invoice.to.email, 110, y + 15);
  doc.text(invoice.to.phone, 110, y + 20);
  doc.text(invoice.to.address, 110, y + 25);

  // Items table
  autoTable(doc, {
    startY: y + 35,
    head: [['Description', 'Qty', 'Rate', 'Amount']],
    body: invoice.items.map((item) => [
      item.description,
      String(item.quantity),
      formatCurrency(item.rate, invoice.currency),
      formatCurrency(item.quantity * item.rate, invoice.currency),
    ]),
    theme: 'striped',
    headStyles: { fillColor: [59, 130, 246], textColor: 255 },
    styles: { fontSize: 11 },
    foot: [
      ['', '', 'Subtotal', formatCurrency(subtotal(invoice), invoice.currency)],
      ['', '', `Tax (${invoice.taxRate}%)`, formatCurrency(taxAmount(invoice), invoice.currency)],
      ['', '', 'Total', formatCurrency(total(invoice), invoice.currency)],
    ],
    footStyles: { fillColor: [243, 244, 246], textColor: [31, 41, 55], fontStyle: 'bold' },
  });

  const finalY = (doc as any).lastAutoTable?.finalY || 180;
  if (invoice.notes) {
    doc.text('Notes:', 15, finalY + 15);
    doc.setFontSize(10);
    doc.text(invoice.notes, 15, finalY + 22);
  }
  if (invoice.terms) {
    doc.text(`Terms: ${invoice.terms}`, 15, finalY + 35);
  }

  doc.setFontSize(9);
  doc.setTextColor(156, 163, 175);
  doc.text('Generated by Billify', 15, 290);
}

function generateClassic(doc: jsPDF, invoice: Invoice) {
  doc.setTextColor(17, 24, 39);
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.text('INVOICE', 15, 25);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(`#${invoice.number}`, 15, 33);
  doc.text(`Date: ${invoice.date}`, 140, 25);
  doc.text(`Due: ${invoice.dueDate}`, 140, 32);

  doc.setDrawColor(200, 200, 200);
  doc.line(15, 40, 195, 40);

  let y = 55;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('From', 15, y);
  doc.text('Bill To', 110, y);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  if (invoice.from.logo) {
    try { doc.addImage(invoice.from.logo, 'JPEG', 15, y + 2, 18, 18); } catch {}
  }
  doc.text(invoice.from.name || 'Your Company', 15, y + 10);
  doc.text(invoice.from.email, 15, y + 15);
  doc.text(invoice.from.phone, 15, y + 20);
  doc.text(invoice.from.address, 15, y + 25);

  doc.text(invoice.to.name || 'Client Name', 110, y + 10);
  doc.text(invoice.to.email, 110, y + 15);
  doc.text(invoice.to.phone, 110, y + 20);
  doc.text(invoice.to.address, 110, y + 25);

  autoTable(doc, {
    startY: y + 35,
    head: [['Item', 'Description', 'Qty', 'Rate', 'Amount']],
    body: invoice.items.map((item, i) => [
      String(i + 1),
      item.description,
      String(item.quantity),
      formatCurrency(item.rate, invoice.currency),
      formatCurrency(item.quantity * item.rate, invoice.currency),
    ]),
    theme: 'grid',
    headStyles: { fillColor: [31, 41, 55], textColor: 255 },
    styles: { fontSize: 11 },
    foot: [
      ['', '', '', 'Subtotal', formatCurrency(subtotal(invoice), invoice.currency)],
      ['', '', '', `Tax (${invoice.taxRate}%)`, formatCurrency(taxAmount(invoice), invoice.currency)],
      ['', '', '', 'Total', formatCurrency(total(invoice), invoice.currency)],
    ],
  });

  const finalY = (doc as any).lastAutoTable?.finalY || 180;
  if (invoice.notes) {
    doc.setFontSize(10);
    doc.text(`Notes: ${invoice.notes}`, 15, finalY + 15);
  }
  doc.setFontSize(9);
  doc.text('Generated by Billify', 15, 290);
}

function generateMinimal(doc: jsPDF, invoice: Invoice) {
  doc.setTextColor(31, 41, 55);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'normal');
  doc.text('Invoice', 15, 25);

  doc.setFontSize(10);
  doc.text(`#${invoice.number}  ·  ${invoice.date}  ·  Due ${invoice.dueDate}`, 15, 33);

  let y = 55;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('FROM', 15, y);
  doc.text('TO', 110, y);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  if (invoice.from.logo) {
    try { doc.addImage(invoice.from.logo, 'JPEG', 15, y + 3, 16, 16); } catch {}
  }
  doc.text(invoice.from.name || 'Your Company', 15, y + 12);
  doc.text(invoice.from.email, 15, y + 17);
  doc.text(invoice.from.phone, 15, y + 22);
  doc.text(invoice.from.address, 15, y + 27);

  doc.text(invoice.to.name || 'Client Name', 110, y + 12);
  doc.text(invoice.to.email, 110, y + 17);
  doc.text(invoice.to.phone, 110, y + 22);
  doc.text(invoice.to.address, 110, y + 27);

  autoTable(doc, {
    startY: y + 38,
    head: [['Description', 'Qty', 'Rate', 'Amount']],
    body: invoice.items.map((item) => [
      item.description,
      String(item.quantity),
      formatCurrency(item.rate, invoice.currency),
      formatCurrency(item.quantity * item.rate, invoice.currency),
    ]),
    theme: 'plain',
    headStyles: { fontStyle: 'bold', textColor: [31, 41, 55] },
    styles: { fontSize: 10, lineColor: [200, 200, 200], lineWidth: 0.1 },
    foot: [
      ['', '', 'Subtotal', formatCurrency(subtotal(invoice), invoice.currency)],
      ['', '', `Tax (${invoice.taxRate}%)`, formatCurrency(taxAmount(invoice), invoice.currency)],
      ['', '', 'Total', formatCurrency(total(invoice), invoice.currency)],
    ],
    footStyles: { fontStyle: 'bold', textColor: [31, 41, 55] },
  });

  const finalY = (doc as any).lastAutoTable?.finalY || 180;
  if (invoice.notes) {
    doc.setFontSize(10);
    doc.text(`Notes: ${invoice.notes}`, 15, finalY + 14);
  }
  doc.setFontSize(9);
  doc.text('Generated by Billify', 15, 290);
}

function subtotal(invoice: Invoice): number {
  return invoice.items.reduce((sum, item) => sum + item.quantity * item.rate, 0);
}

function taxAmount(invoice: Invoice): number {
  return subtotal(invoice) * (invoice.taxRate / 100);
}

function total(invoice: Invoice): number {
  return subtotal(invoice) + taxAmount(invoice);
}
