'use client';

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Invoice, TemplateType, formatCurrencyPdf, calculateTotals, resolveTaxConfig, taxConfigLabel, rcTotal } from '@/types';
import { SITE_HOST } from '@/lib/site';

// PDF footer brand line for the three template renderers that print the host
// alongside the wordmark. Derived from SITE_HOST (the single source of truth in
// site.ts) so a domain change/rebrand updates every PDF footer in lockstep with
// the rest of the app, and the three intra-file copies can no longer drift from
// each other or from the canonical host. The other renderers print
// 'Generated by Billify' without the host, intentionally.
const FOOTER_WITH_HOST = `Generated by Billify — ${SITE_HOST}`;

// Template id → renderer dispatch. Keyed by the full TemplateType union via
// Record<TemplateType, …>, so the mapping is exhaustiveness-checked at compile
// time: add a new TemplateType without a renderer here and tsc errors, instead
// of the old if/else chain's silent fall-through to generateCreative (which is
// how `executive` came to render as Creative — the dedicated generateExecutive
// existed but the chain never dispatched to it). Function declarations are
// hoisted, so the renderers defined below are in scope when this const
// initializes.
const TEMPLATE_RENDERERS: Record<TemplateType, (doc: jsPDF, invoice: Invoice) => void> = {
  modern: generateModern,
  classic: generateClassic,
  minimal: generateMinimal,
  clean: generateClean,
  bold: generateBold,
  executive: generateExecutive,
  corporate: generateCorporate,
  startup: generateStartup,
  freelancer: generateFreelancer,
  agency: generateAgency,
  consulting: generateConsulting,
  creative: generateCreative,
};

// Shared autoTable `foot` (Subtotal / Tax (label rate%) / Total rows) for every
// renderer. The 12 renderers' foot blocks were byte-identical except for the
// column count (4 for every table, 5 for Classic) and Consulting's uppercase
// labels — and had just been re-edited in lockstep (subtotal/taxAmount/total →
// calculateTotals), which is the moment to factor: adding a row (discount,
// shipping, rounding) or changing the tax-label format now lands in one place
// instead of 12 synchronized edits with no build signal if one is missed.
//
// `columns` is the table's column count (matches the `head` array length, so
// it's self-evident at the call site — 4 for every template, 5 for Classic). The
// leading blank count is derived as `columns - 2` (the label + amount occupy the
// last two cells), so each row yields exactly `columns` cells and aligns with the
// head — e.g. a 4-column table foot row is ['','','Subtotal', amount] (4 cells).
// Callers MUST pass the column count, NOT the blank count: an earlier form took
// the blank count directly and every call site passed columns-1 instead of
// columns-2, adding an extra blank cell to every foot row and misaligning the
// Subtotal/Tax/Total amounts across all 12 templates. Taking `columns` and
// deriving the blanks here removes that off-by-one foot-gun. `labels` defaults
// to the title-case strings every renderer but Consulting uses.
//
// Issue #21 — the tax row now uses the TaxConfig label ("VAT (20%)" instead of
// "Tax (20%)"), and a reverse-charge invoice reports the tax amount but does NOT
// add it to the total (the buyer self-accounts for it on their own return).
// Both come from resolveTaxConfig(invoice) so a legacy invoice with just
// taxRate renders identically (label "Tax", reverseCharge false).
function totalsFoot(
  invoice: Invoice,
  totals: { subtotal: number; tax: number; total: number },
  columns: number,
  labels: { subtotal: string; tax: string; total: string } = { subtotal: 'Subtotal', tax: 'Tax', total: 'Total' },
): string[][] {
  const cfg = resolveTaxConfig(invoice);
  // Reverse-charge: tax is reported (shown on its own line, annotated) but the
  // total is just the subtotal. rcTotal returns {tax, total} with tax preserved
  // and total collapsed to subtotal when reverseCharge is true; the non-RC path
  // returns the original totals unchanged.
  const rc = rcTotal(totals, cfg.reverseCharge);
  const taxLabel = taxConfigLabel(cfg);
  const blanks: string[] = Array.from({ length: columns - 2 }, () => '');
  return [
    [...blanks, labels.subtotal, formatCurrencyPdf(totals.subtotal, invoice.currency)],
    // Tax row: "<label> (<rate>%)" — e.g. "VAT (20%)" or "Sales Tax (8.5%)".
    // On a reverse-charge invoice the rate/label still surface (the buyer needs
    // to know what to self-account), but the total below excludes the tax.
    [...blanks, `${labels.tax === 'Tax' ? taxLabel : labels.tax} (${cfg.rate}%)`, formatCurrencyPdf(rc.tax, invoice.currency)],
    [...blanks, labels.total, formatCurrencyPdf(rc.total, invoice.currency)],
  ];
}

// ─── Issue #21: reverse-charge + tax-ID annotation (post-table) ──────────
// Renders the "VAT No: <id>" and "Reverse Charge" annotations BELOW the totals
// table, in small gray type, when applicable. Returns the Y after the last line
// so the renderer's notes/terms can follow. No-op (returns baseY) when there's
// nothing to draw, so a legacy invoice with no TaxConfig renders exactly as
// before. The annotation is intentionally SEPARATE from the inline party-block
// details (drawDetailsInline etc.) — EN 16931 puts the tax-line annotation next
// to the totals it relates to, while the seller/buyer identity sits with the
// parties. Placing it here also means it lands on the same page as the total
// regardless of how long the items table grew.
function drawTaxAnnotation(
  doc: jsPDF,
  invoice: Invoice,
  baseY: number,
  x: number,
): number {
  const cfg = resolveTaxConfig(invoice);
  const lines: string[] = [];
  // "VAT No: <id>" / "GST No: <id>" / etc. — uses the tax-line label so the
  // registration number is disambiguated from the seller-identity taxId that
  // already renders inline with the From block. Only shown when there's an
  // actual taxId (resolveTaxConfig falls back to from.taxId, so a user who set
  // the seller taxId but never touched TaxConfig still sees it surface here).
  if (cfg.taxId) {
    const noLabel = cfg.label === 'Custom' && cfg.customLabel ? cfg.customLabel : taxConfigLabel(cfg);
    lines.push(`${noLabel} No: ${cfg.taxId}`);
  }
  if (cfg.buyerTaxId) {
    lines.push(`Buyer ${taxConfigLabel(cfg)} No: ${cfg.buyerTaxId}`);
  }
  if (cfg.reverseCharge) {
    // The canonical EU reverse-charge wording. The buyer's registration number
    // (above) and this annotation together satisfy the EN 16931 requirement.
    lines.push('Reverse Charge');
  }
  if (!lines.length) return baseY;
  const prevSize = doc.getFontSize();
  const prevColor = doc.getTextColor();
  const prevFont = doc.getFont();
  doc.setFontSize(8);
  doc.setTextColor(107, 114, 128);
  doc.setFont('helvetica', 'normal');
  lines.forEach((line, i) => doc.text(line, x, baseY + 5 + i * 4));
  doc.setFontSize(prevSize);
  doc.setTextColor(prevColor);
  doc.setFont(prevFont.fontName, prevFont.fontStyle);
  return baseY + 5 + lines.length * 4;
}

// ─── Compliance detail rendering (EN 16931) ──────────────────────────────
// The optional compliance/payment fields (seller + buyer tax IDs, PO #, SEPA
// bank details) render INLINE in the From/To party-block region — NOT below the
// items table. Placing them above the table matches EN 16931 layout guidance
// (seller/buyer tax info belongs with the parties, not after totals) and, just
// as importantly, stops the block from being clipped off the bottom of the page
// on long invoices — the failure mode of the old below-totals placement, which
// drew the details at a fixed `finalY + 48` that ran past the page edge once the
// items table grew past one page.
//
// The 12 templates fall into three placement shapes, each served by one helper:
//  • Side-by-side From/To (Modern, Classic, Minimal, Clean, Bold, Executive,
//    Corporate): the two address blocks share a baseline, so seller lines sit
//    under the From column and buyer lines under the To column. → drawDetailsInline
//  • Single-column stacked (Freelancer): From then To in one column; each
//    party's lines fold into the running y so the trailing block/table push down
//    past them (no overlap on a 3-4-line seller block). → drawPartyDetails x2
//  • Seller block with no readable room beside it — colored band (Startup
//    sidebar, Agency dark header), compact right-aligned header (Consulting), or
//    art layout (Creative): gray 8pt text would be illegible on the band or
//    collide with the accent stripe, so seller + buyer render TOGETHER in the
//    body just above the table, "From"/"To"-prefixed so two same-named fields
//    (e.g. the two "Tax ID / VAT" lines) stay unambiguous in one column.
//    → drawDetailsCombined

// Seller (From) compliance lines: tax ID + payment account details.
function sellerDetailLines(invoice: Invoice): string[] {
  const lines: string[] = [];
  if (invoice.from.taxId) lines.push(`Tax ID / VAT: ${invoice.from.taxId}`);
  const pm = invoice.paymentMeans;
  if (pm) {
    if (pm.iban) lines.push(`IBAN: ${pm.iban}`);
    if (pm.bic) lines.push(`BIC / SWIFT: ${pm.bic}`);
    if (pm.accountName) lines.push(`Account: ${pm.accountName}`);
  }
  return lines;
}

// Buyer (To) compliance lines: tax ID + purchase order.
function buyerDetailLines(invoice: Invoice): string[] {
  const lines: string[] = [];
  if (invoice.to.taxId) lines.push(`Tax ID / VAT: ${invoice.to.taxId}`);
  if (invoice.purchaseOrder) lines.push(`PO: ${invoice.purchaseOrder}`);
  return lines;
}

// Draw one party's compliance `lines` beneath its address block, starting at
// `baseY + 6` (just under the last address line) at 4mm line height, gray 8pt.
// Returns the Y after the last line so the caller can push the items table (or
// the next party block) below it, and restores font/size/color so the renderer's
// own typography is unaffected. No-op (returns `baseY`) when there's nothing to
// draw, so a template with no compliance data is laid out exactly as before.
function drawPartyDetails(doc: jsPDF, lines: string[], x: number, baseY: number): number {
  if (!lines.length) return baseY;
  const prevSize = doc.getFontSize();
  const prevColor = doc.getTextColor();
  const prevFont = doc.getFont();
  doc.setFontSize(8);
  doc.setTextColor(107, 114, 128);
  doc.setFont('helvetica', 'normal');
  lines.forEach((line, i) => doc.text(line, x, baseY + 6 + i * 4));
  doc.setFontSize(prevSize);
  doc.setTextColor(prevColor);
  doc.setFont(prevFont.fontName, prevFont.fontStyle);
  return baseY + 6 + lines.length * 4;
}

// Side-by-side placement for templates whose From and To blocks share a
// baseline: seller lines under `fromX`, buyer lines under `toX`, both beneath
// the same `baseY` (the last address line of both blocks). Returns the Y below
// whichever party grew taller, so the items table clears both columns at once.
function drawDetailsInline(doc: jsPDF, invoice: Invoice, fromX: number, toX: number, baseY: number): number {
  const fromEnd = drawPartyDetails(doc, sellerDetailLines(invoice), fromX, baseY);
  const toEnd = drawPartyDetails(doc, buyerDetailLines(invoice), toX, baseY);
  return Math.max(fromEnd, toEnd);
}

// Combined placement for templates whose seller block has no adjacent readable
// area (colored band / compact header / art layout): seller + buyer lines render
// together at one body column, "From"/"To"-prefixed so two same-named fields
// stay disambiguated. `x`/`baseY` is the body anchor (usually just beneath the
// To block, above the items table).
function drawDetailsCombined(doc: jsPDF, invoice: Invoice, x: number, baseY: number): number {
  const seller = sellerDetailLines(invoice).map((l) => `From ${l}`);
  const buyer = buyerDetailLines(invoice).map((l) => `To ${l}`);
  return drawPartyDetails(doc, [...seller, ...buyer], x, baseY);
}

// Render `invoice`'s selected template into an EXISTING doc, without the
// HTML-sanitization wrapper (callers pass already-trusted input). Exported so
// generatePDF can reuse it AND so tests can drive a template with a real jsPDF
// instance (observing doc.text coordinates for layout assertions) without
// parsing PDF bytes or going through the blob round-trip.
export function renderTemplateInto(doc: jsPDF, invoice: Invoice): void {
  TEMPLATE_RENDERERS[invoice.template](doc, invoice);
}

export function generatePDF(invoice: Invoice): Blob {
  const doc = new jsPDF();

  // R7 fix: removed clean() regex — jsPDF's doc.text() renders literal text and
  // never parses HTML, so there was nothing to sanitize. The regex /<[^>]*>/g
  // was silently deleting real user content (e.g. "net 14, payment < 30 days"
  // became "net 14, payment "). clean() is now a passthrough.
  const clean = (s: string) => s;
  const safeInvoice: Invoice = {
    ...invoice,
    number: clean(invoice.number),
    from: {
      ...invoice.from,
      name: clean(invoice.from.name),
      email: clean(invoice.from.email),
      phone: clean(invoice.from.phone),
      address: clean(invoice.from.address),
      taxId: clean(invoice.from.taxId ?? ''),
      addressLine2: clean(invoice.from.addressLine2 ?? ''),
      city: clean(invoice.from.city ?? ''),
      region: clean(invoice.from.region ?? ''),
      postalCode: clean(invoice.from.postalCode ?? ''),
      country: clean(invoice.from.country ?? ''),
    },
    to: {
      ...invoice.to,
      name: clean(invoice.to.name),
      email: clean(invoice.to.email),
      phone: clean(invoice.to.phone),
      address: clean(invoice.to.address),
      taxId: clean(invoice.to.taxId ?? ''),
      addressLine2: clean(invoice.to.addressLine2 ?? ''),
      city: clean(invoice.to.city ?? ''),
      region: clean(invoice.to.region ?? ''),
      postalCode: clean(invoice.to.postalCode ?? ''),
      country: clean(invoice.to.country ?? ''),
    },
    items: invoice.items.map(item => ({
      ...item,
      description: clean(item.description),
      unitCode: item.unitCode ? clean(item.unitCode) : item.unitCode,
    })),
    notes: clean(invoice.notes),
    terms: clean(invoice.terms),
    purchaseOrder: invoice.purchaseOrder ? clean(invoice.purchaseOrder) : invoice.purchaseOrder,
    leitwegId: invoice.leitwegId ? clean(invoice.leitwegId) : invoice.leitwegId,
    paymentMeans: invoice.paymentMeans ? {
      ...invoice.paymentMeans,
      code: clean(invoice.paymentMeans.code),
      iban: clean(invoice.paymentMeans.iban ?? ''),
      bic: clean(invoice.paymentMeans.bic ?? ''),
      accountName: clean(invoice.paymentMeans.accountName ?? ''),
    } : invoice.paymentMeans,
  };

  renderTemplateInto(doc, safeInvoice);

  return doc.output('blob');
}

function generateModern(doc: jsPDF, invoice: Invoice) {
  const totals = calculateTotals(invoice.items, invoice.taxRate);
  // Header gradient-ish band
  doc.setFillColor(59, 130, 246);
  doc.rect(0, 0, 210, 40, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('INVOICE', 15, 25);

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`#${invoice.number}`, 15, 32);

  doc.setFontSize(10);
  doc.text(`Date: ${invoice.date}`, 160, 20);
  doc.text(`Due: ${invoice.dueDate}`, 160, 26);

  // From / To
  let y = 55;
  doc.setTextColor(31, 41, 55);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('From:', 15, y);
  if (invoice.from.logo) {
    try { doc.addImage(invoice.from.logo, 'JPEG', 15, y + 2, 20, 20); } catch {}
  }
  doc.setFont('helvetica', 'normal');
  doc.text(invoice.from.name || 'Your Company', 15, y + 10);
  doc.text(invoice.from.email, 15, y + 15);
  doc.text(invoice.from.phone, 15, y + 20);
  doc.text(invoice.from.address, 15, y + 25);

  doc.setFont('helvetica', 'bold');
  doc.text('Bill To:', 110, y);
  doc.setFont('helvetica', 'normal');
  doc.text(invoice.to.name || 'Client Name', 110, y + 10);
  doc.text(invoice.to.email, 110, y + 15);
  doc.text(invoice.to.phone, 110, y + 20);
  doc.text(invoice.to.address, 110, y + 25);

  // Compliance details inline beneath From/To (tax IDs, PO, bank info)
  const detailsY = drawDetailsInline(doc, invoice, 15, 110, y + 25);

  // Items table
  autoTable(doc, {
    startY: Math.max(y + 35, detailsY + 5),
    head: [['Description', 'Qty', 'Rate', 'Amount']],
    body: invoice.items.map((item) => [
      item.description,
      String(item.quantity),
      formatCurrencyPdf(item.rate, invoice.currency),
      formatCurrencyPdf(item.quantity * item.rate, invoice.currency),
    ]),
    theme: 'striped',
    headStyles: { fillColor: [59, 130, 246], textColor: 255 },
    styles: { fontSize: 11 },
    foot: totalsFoot(invoice, totals, 4),
    footStyles: { fillColor: [243, 244, 246], textColor: [31, 41, 55], fontStyle: 'bold' },
  });

  const finalY = (doc as any).lastAutoTable?.finalY || 180;
  // Issue #21: VAT/GST No + Reverse Charge annotation. No-op (returns finalY)
  // when the invoice has no tax config, so a legacy invoice's layout is
  // unchanged. taxY pushes notes/terms down past the annotation so a 1-3 line
  // "VAT No / Buyer VAT No / Reverse Charge" block can't overlap the notes.
  const taxY = drawTaxAnnotation(doc, invoice, finalY, 15);
  if (invoice.notes) {
    doc.text('Notes:', 15, taxY + 15);
    doc.setFontSize(10);
    doc.text(invoice.notes, 15, taxY + 22);
  }
  if (invoice.terms) {
    doc.text(`Terms: ${invoice.terms}`, 15, taxY + 35);
  }

  doc.setFontSize(9);
  doc.setTextColor(156, 163, 175);
  doc.text('Generated by Billify', 15, 290);
}

function generateClassic(doc: jsPDF, invoice: Invoice) {
  const totals = calculateTotals(invoice.items, invoice.taxRate);
  doc.setTextColor(17, 24, 39);
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.text('INVOICE', 15, 25);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(`#${invoice.number}`, 15, 33);
  doc.text(`Date: ${invoice.date}`, 140, 25);
  doc.text(`Due: ${invoice.dueDate}`, 140, 32);

  doc.setDrawColor(200, 200, 200);
  doc.line(15, 40, 195, 40);

  let y = 55;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('From', 15, y);
  doc.text('Bill To', 110, y);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  if (invoice.from.logo) {
    try { doc.addImage(invoice.from.logo, 'JPEG', 15, y + 2, 18, 18); } catch {}
  }
  doc.text(invoice.from.name || 'Your Company', 15, y + 10);
  doc.text(invoice.from.email, 15, y + 15);
  doc.text(invoice.from.phone, 15, y + 20);
  doc.text(invoice.from.address, 15, y + 25);

  doc.text(invoice.to.name || 'Client Name', 110, y + 10);
  doc.text(invoice.to.email, 110, y + 15);
  doc.text(invoice.to.phone, 110, y + 20);
  doc.text(invoice.to.address, 110, y + 25);

  // Compliance details (tax IDs, PO, bank info) inline beneath From/To, above
  // the items table — EN 16931 layout, no below-totals clipping.
  const detailsY = drawDetailsInline(doc, invoice, 15, 110, y + 25);

  autoTable(doc, {
    startY: Math.max(y + 35, detailsY + 5),
    head: [['Item', 'Description', 'Qty', 'Rate', 'Amount']],
    body: invoice.items.map((item, i) => [
      String(i + 1),
      item.description,
      String(item.quantity),
      formatCurrencyPdf(item.rate, invoice.currency),
      formatCurrencyPdf(item.quantity * item.rate, invoice.currency),
    ]),
    theme: 'grid',
    headStyles: { fillColor: [31, 41, 55], textColor: 255 },
    styles: { fontSize: 11 },
    foot: totalsFoot(invoice, totals, 5),
  });

  const finalY = (doc as any).lastAutoTable?.finalY || 180;
  const taxY = drawTaxAnnotation(doc, invoice, finalY, 15);
  if (invoice.notes) {
    doc.setFontSize(10);
    doc.text(`Notes: ${invoice.notes}`, 15, taxY + 15);
  }
  doc.setFontSize(9);
  doc.text('Generated by Billify', 15, 290);
}

function generateMinimal(doc: jsPDF, invoice: Invoice) {
  const totals = calculateTotals(invoice.items, invoice.taxRate);
  doc.setTextColor(31, 41, 55);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'normal');
  doc.text('Invoice', 15, 25);

  doc.setFontSize(10);
  doc.text(`#${invoice.number}  ·  ${invoice.date}  ·  Due ${invoice.dueDate}`, 15, 33);

  let y = 55;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('FROM', 15, y);
  doc.text('TO', 110, y);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  if (invoice.from.logo) {
    try { doc.addImage(invoice.from.logo, 'JPEG', 15, y + 3, 16, 16); } catch {}
  }
  doc.text(invoice.from.name || 'Your Company', 15, y + 12);
  doc.text(invoice.from.email, 15, y + 17);
  doc.text(invoice.from.phone, 15, y + 22);
  doc.text(invoice.from.address, 15, y + 27);

  doc.text(invoice.to.name || 'Client Name', 110, y + 12);
  doc.text(invoice.to.email, 110, y + 17);
  doc.text(invoice.to.phone, 110, y + 22);
  doc.text(invoice.to.address, 110, y + 27);

  // Compliance details (tax IDs, PO, bank info) inline beneath From/To, above
  // the items table — EN 16931 layout, no below-totals clipping.
  const detailsY = drawDetailsInline(doc, invoice, 15, 110, y + 27);

  autoTable(doc, {
    startY: Math.max(y + 38, detailsY + 5),
    head: [['Description', 'Qty', 'Rate', 'Amount']],
    body: invoice.items.map((item) => [
      item.description,
      String(item.quantity),
      formatCurrencyPdf(item.rate, invoice.currency),
      formatCurrencyPdf(item.quantity * item.rate, invoice.currency),
    ]),
    theme: 'plain',
    headStyles: { fontStyle: 'bold', textColor: [31, 41, 55] },
    styles: { fontSize: 10, lineColor: [200, 200, 200], lineWidth: 0.1 },
    foot: totalsFoot(invoice, totals, 4),
    footStyles: { fontStyle: 'bold', textColor: [31, 41, 55] },
  });

  const finalY = (doc as any).lastAutoTable?.finalY || 180;
  const taxY = drawTaxAnnotation(doc, invoice, finalY, 15);
  if (invoice.notes) {
    doc.setFontSize(10);
    doc.text(`Notes: ${invoice.notes}`, 15, taxY + 14);
  }
  doc.setFontSize(9);
  doc.text('Generated by Billify', 15, 290);
}

// ─── Clean Template ────────────────────────────────────
// White space, subtle borders, refined typography
function generateClean(doc: jsPDF, invoice: Invoice) {
  const totals = calculateTotals(invoice.items, invoice.taxRate);
  doc.setTextColor(51, 65, 85);
  doc.setFontSize(26);
  doc.setFont('helvetica', 'normal');
  doc.text('Invoice', 15, 28);

  doc.setFontSize(9);
  doc.text(`#${invoice.number}`, 15, 36);

  doc.setTextColor(100, 116, 139);
  doc.text(`Date: ${invoice.date}`, 160, 28);
  doc.text(`Due: ${invoice.dueDate}`, 160, 34);

  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.3);
  doc.line(15, 45, 195, 45);

  let y = 58;
  doc.setTextColor(51, 65, 85);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Billed From', 15, y);
  doc.text('Billed To', 110, y);

  doc.setFont('helvetica', 'normal');
  if (invoice.from.logo) {
    try { doc.addImage(invoice.from.logo, 'JPEG', 15, y + 3, 18, 18); } catch {}
  }
  doc.text(invoice.from.name || 'Your Company', 15, y + 11);
  doc.text(invoice.from.email, 15, y + 16);
  doc.text(invoice.from.phone, 15, y + 21);
  doc.text(invoice.from.address, 15, y + 26);

  doc.text(invoice.to.name || 'Client Name', 110, y + 11);
  doc.text(invoice.to.email, 110, y + 16);
  doc.text(invoice.to.phone, 110, y + 21);
  doc.text(invoice.to.address, 110, y + 26);

  // Compliance details (tax IDs, PO, bank info) inline beneath From/To, above
  // the items table — EN 16931 layout, no below-totals clipping.
  const detailsY = drawDetailsInline(doc, invoice, 15, 110, y + 26);

  autoTable(doc, {
    startY: Math.max(y + 34, detailsY + 5),
    head: [['Description', 'Qty', 'Rate', 'Amount']],
    body: invoice.items.map((item) => [
      item.description,
      String(item.quantity),
      formatCurrencyPdf(item.rate, invoice.currency),
      formatCurrencyPdf(item.quantity * item.rate, invoice.currency),
    ]),
    theme: 'plain',
    headStyles: {
      fontStyle: 'bold',
      textColor: [51, 65, 85],
      lineColor: [203, 213, 225],
      lineWidth: 0.5,
    },
    styles: { fontSize: 10, lineColor: [226, 232, 240], lineWidth: 0.3 },
    foot: totalsFoot(invoice, totals, 4),
    footStyles: { fontStyle: 'bold', textColor: [15, 23, 42] },
  });

  const finalY = (doc as any).lastAutoTable?.finalY || 180;
  const taxY = drawTaxAnnotation(doc, invoice, finalY, 15);
  if (invoice.notes) {
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text(`Notes: ${invoice.notes}`, 15, taxY + 14);
  }
  if (invoice.terms) {
    doc.text(`Terms: ${invoice.terms}`, 15, taxY + 22);
  }
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text('Generated by Billify', 15, 290);
}

// ─── Bold Template ────────────────────────────────────
// High contrast, large type, strong visual hierarchy
function generateBold(doc: jsPDF, invoice: Invoice) {
  const totals = calculateTotals(invoice.items, invoice.taxRate);
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, 210, 50, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(32);
  doc.setFont('helvetica', 'bold');
  doc.text('INVOICE', 15, 30);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(`#${invoice.number}`, 15, 40);
  doc.text(`Date: ${invoice.date}`, 140, 30);
  doc.text(`Due: ${invoice.dueDate}`, 140, 38);

  let y = 65;
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('FROM', 15, y);
  doc.text('TO', 110, y);

  doc.setFont('helvetica', 'normal');
  if (invoice.from.logo) {
    try { doc.addImage(invoice.from.logo, 'JPEG', 15, y + 3, 18, 18); } catch {}
  }
  doc.text(invoice.from.name || 'Your Company', 15, y + 11);
  doc.text(invoice.from.email, 15, y + 16);
  doc.text(invoice.from.phone, 15, y + 21);
  doc.text(invoice.from.address, 15, y + 26);

  doc.text(invoice.to.name || 'Client Name', 110, y + 11);
  doc.text(invoice.to.email, 110, y + 16);
  doc.text(invoice.to.phone, 110, y + 21);
  doc.text(invoice.to.address, 110, y + 26);

  // Compliance details (tax IDs, PO, bank info) inline beneath From/To, above
  // the table — EN 16931 layout, no below-totals clipping.
  const detailsY = drawDetailsInline(doc, invoice, 15, 110, y + 26);

  autoTable(doc, {
    startY: Math.max(y + 34, detailsY + 5),
    head: [['Description', 'Qty', 'Rate', 'Amount']],
    body: invoice.items.map((item) => [
      item.description,
      String(item.quantity),
      formatCurrencyPdf(item.rate, invoice.currency),
      formatCurrencyPdf(item.quantity * item.rate, invoice.currency),
    ]),
    theme: 'grid',
    headStyles: { fillColor: [15, 23, 42], textColor: 255, fontSize: 11 },
    styles: { fontSize: 11, textColor: [15, 23, 42] },
    foot: totalsFoot(invoice, totals, 4),
    footStyles: { fillColor: [241, 245, 249], textColor: [15, 23, 42], fontStyle: 'bold', fontSize: 12 },
  });

  const finalY = (doc as any).lastAutoTable?.finalY || 180;
  const taxY = drawTaxAnnotation(doc, invoice, finalY, 15);
  if (invoice.notes) {
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text(`Notes: ${invoice.notes}`, 15, taxY + 14);
  }
  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184);
  doc.text('Generated by Billify', 15, 290);
}

// ─── Executive Template ────────────────────────────────────
// Formal, refined layout with accent lines and sophisticated typography
function generateExecutive(doc: jsPDF, invoice: Invoice) {
  const totals = calculateTotals(invoice.items, invoice.taxRate);
  // Subtle top accent line
  doc.setFillColor(180, 83, 9); // amber/teal accent
  doc.rect(0, 0, 210, 3, 'F');

  doc.setTextColor(51, 65, 85);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('TAX INVOICE', 15, 22);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`Invoice #: ${invoice.number}`, 15, 30);
  doc.text(`Date: ${invoice.date}`, 160, 22);
  doc.text(`Due Date: ${invoice.dueDate}`, 160, 28);

  doc.setDrawColor(180, 83, 9);
  doc.setLineWidth(0.4);
  doc.line(15, 36, 195, 36);

  let y = 48;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(100, 116, 139);
  doc.text('BILLED FROM', 15, y);
  doc.text('BILLED TO', 110, y);

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(51, 65, 85);
  if (invoice.from.logo) {
    try { doc.addImage(invoice.from.logo, 'JPEG', 15, y + 3, 16, 16); } catch {}
  }
  doc.text(invoice.from.name || 'Your Company', 15, y + 10);
  doc.text(invoice.from.email, 15, y + 15);
  doc.text(invoice.from.phone, 15, y + 20);
  doc.text(invoice.from.address, 15, y + 25);

  doc.text(invoice.to.name || 'Client Name', 110, y + 10);
  doc.text(invoice.to.email, 110, y + 15);
  doc.text(invoice.to.phone, 110, y + 20);
  doc.text(invoice.to.address, 110, y + 25);

  // Compliance details (tax IDs, PO, bank info) inline beneath From/To, above
  // the items table — EN 16931 layout, no below-totals clipping.
  const detailsY = drawDetailsInline(doc, invoice, 15, 110, y + 25);

  autoTable(doc, {
    startY: Math.max(y + 32, detailsY + 5),
    head: [['Description', 'Qty', 'Rate', 'Amount']],
    body: invoice.items.map((item) => [
      item.description,
      String(item.quantity),
      formatCurrencyPdf(item.rate, invoice.currency),
      formatCurrencyPdf(item.quantity * item.rate, invoice.currency),
    ]),
    theme: 'striped',
    headStyles: {
      fillColor: [51, 65, 85],
      textColor: 255,
      fontSize: 10,
    },
    styles: { fontSize: 10, textColor: [51, 65, 85] },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    foot: totalsFoot(invoice, totals, 4),
    footStyles: { fillColor: [241, 245, 249], textColor: [15, 23, 42], fontStyle: 'bold' },
  });

  const finalY = (doc as any).lastAutoTable?.finalY || 180;
  const taxY = drawTaxAnnotation(doc, invoice, finalY, 15);
  if (invoice.notes) {
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text(`Notes: ${invoice.notes}`, 15, taxY + 14);
  }
  if (invoice.terms) {
    doc.text(`Payment Terms: ${invoice.terms}`, 15, taxY + 22);
  }
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text(FOOTER_WITH_HOST, 15, 290);
}

// ─── Corporate Template (Pro) ────────────────────────────
// Two-column header, business-formal, blue accent line
function generateCorporate(doc: jsPDF, invoice: Invoice) {
  const totals = calculateTotals(invoice.items, invoice.taxRate);
  // Top accent band
  doc.setFillColor(30, 64, 175); // blue-800
  doc.rect(0, 0, 210, 4, 'F');

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('INVOICE', 15, 22);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(`Invoice No: ${invoice.number}`, 15, 30);
  doc.text(`Issue Date: ${invoice.date}`, 15, 35);
  doc.text(`Due Date: ${invoice.dueDate}`, 15, 40);

  // Right: company logo/name
  if (invoice.from.logo) {
    try { doc.addImage(invoice.from.logo, 'JPEG', 165, 14, 30, 14); } catch {}
  }
  doc.setTextColor(30, 64, 175);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text(invoice.from.name || 'Your Company', 195, 36, { align: 'right' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text(invoice.from.email, 195, 41, { align: 'right' });
  doc.text(invoice.from.phone, 195, 45, { align: 'right' });

  // Accent divider
  doc.setDrawColor(30, 64, 175);
  doc.setLineWidth(0.5);
  doc.line(15, 50, 195, 50);

  let y = 62;
  doc.setTextColor(30, 64, 175);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.text('BILLED FROM', 15, y);
  doc.text('BILLED TO', 110, y);

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(10);
  doc.text(invoice.from.name || 'Your Company', 15, y + 7);
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text(invoice.from.email, 15, y + 12);
  doc.text(invoice.from.address, 15, y + 17);
  doc.text(invoice.from.phone, 15, y + 22);

  doc.setFontSize(10);
  doc.setTextColor(15, 23, 42);
  doc.text(invoice.to.name || 'Client Name', 110, y + 7);
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text(invoice.to.email, 110, y + 12);
  doc.text(invoice.to.address, 110, y + 17);
  doc.text(invoice.to.phone, 110, y + 22);

  // Compliance details (tax IDs, PO, bank info) inline beneath From/To, above
  // the items table — EN 16931 layout, no below-totals clipping.
  const detailsY = drawDetailsInline(doc, invoice, 15, 110, y + 22);

  autoTable(doc, {
    startY: Math.max(y + 30, detailsY + 5),
    head: [['Description', 'Qty', 'Rate', 'Amount']],
    body: invoice.items.map((item) => [
      item.description,
      String(item.quantity),
      formatCurrencyPdf(item.rate, invoice.currency),
      formatCurrencyPdf(item.quantity * item.rate, invoice.currency),
    ]),
    theme: 'striped',
    headStyles: { fillColor: [30, 64, 175], textColor: 255, fontSize: 9, fontStyle: 'bold' },
    styles: { fontSize: 9, textColor: [15, 23, 42] },
    alternateRowStyles: { fillColor: [239, 246, 255] },
    foot: totalsFoot(invoice, totals, 4),
    footStyles: { fillColor: [30, 64, 175], textColor: 255, fontStyle: 'bold' },
  });

  const finalY = (doc as any).lastAutoTable?.finalY || 180;
  const taxY = drawTaxAnnotation(doc, invoice, finalY, 15);
  if (invoice.notes) {
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);
    doc.text(`Notes: ${invoice.notes}`, 15, taxY + 12);
  }
  if (invoice.terms) {
    doc.text(`Terms: ${invoice.terms}`, 15, taxY + 20);
  }
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text(FOOTER_WITH_HOST, 15, 290);
}

// ─── Startup Template (Pro) ────────────────────────────────
// Energetic, brand-color sidebar, modern SaaS look
function generateStartup(doc: jsPDF, invoice: Invoice) {
  const totals = calculateTotals(invoice.items, invoice.taxRate);
  // Left sidebar band
  doc.setFillColor(124, 58, 237); // purple-600
  doc.rect(0, 0, 60, 297, 'F');

  // Logo / brand on sidebar
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text(invoice.from.name || 'Your Brand', 30, 30, { align: 'center' });

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text(invoice.from.email, 30, 40, { align: 'center' });
  doc.text(invoice.from.phone, 30, 45, { align: 'center' });

  // Big "INVOICE" rotated on sidebar
  doc.setFontSize(40);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  // Simple horizontal "INVOICE" — rotation would require angle math
  doc.text('INVOICE', 30, 200, { align: 'center' });
  doc.setFontSize(10);
  doc.text(`#${invoice.number}`, 30, 210, { align: 'center' });

  // Right content area
  let y = 30;
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Invoice', 70, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(`Date: ${invoice.date}`, 70, y);
  y += 5;
  doc.text(`Due: ${invoice.dueDate}`, 70, y);
  y += 12;

  doc.setTextColor(124, 58, 237);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.text('BILLED TO', 70, y);
  y += 5;
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text(invoice.to.name || 'Client Name', 70, y);
  y += 5;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text(invoice.to.email, 70, y);
  y += 4;
  doc.text(invoice.to.phone, 70, y);
  y += 4;
  doc.text(invoice.to.address, 70, y);
  // The seller block lives on the colored sidebar — gray compliance text would
  // be illegible on the purple band — so seller + buyer details render together
  // in the body just above the table ("From/To"-prefixed to stay unambiguous).
  const detailsY = drawDetailsCombined(doc, invoice, 70, y);
  y = Math.max(y + 10, detailsY + 5);

  autoTable(doc, {
    startY: y,
    margin: { left: 70 },
    head: [['Description', 'Qty', 'Rate', 'Amount']],
    body: invoice.items.map((item) => [
      item.description,
      String(item.quantity),
      formatCurrencyPdf(item.rate, invoice.currency),
      formatCurrencyPdf(item.quantity * item.rate, invoice.currency),
    ]),
    theme: 'plain',
    headStyles: { fillColor: [124, 58, 237], textColor: 255, fontSize: 9, fontStyle: 'bold' },
    styles: { fontSize: 9, textColor: [15, 23, 42], lineColor: [226, 232, 240], lineWidth: 0.2 },
    foot: totalsFoot(invoice, totals, 4),
    footStyles: { fontStyle: 'bold', textColor: [124, 58, 237] },
  });

  const finalY = (doc as any).lastAutoTable?.finalY || 180;
  const taxY = drawTaxAnnotation(doc, invoice, finalY, 70);
  if (invoice.notes) {
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text(`Notes: ${invoice.notes}`, 70, taxY + 12);
  }
  doc.setFontSize(7);
  doc.setTextColor(148, 163, 184);
  doc.text('Generated by Billify', 70, 290);
}

// ─── Freelancer Template (Pro) ─────────────────────────────
// Single column, generous whitespace, accent sidebar
function generateFreelancer(doc: jsPDF, invoice: Invoice) {
  const totals = calculateTotals(invoice.items, invoice.taxRate);
  // Accent vertical line on left
  doc.setFillColor(236, 72, 153); // pink-500
  doc.rect(0, 0, 5, 297, 'F');

  let y = 30;
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(28);
  doc.setFont('helvetica', 'light');
  doc.text('Invoice', 20, y);
  y += 10;

  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(`#${invoice.number}  •  ${invoice.date}  •  Due ${invoice.dueDate}`, 20, y);
  y += 18;

  // From section
  doc.setTextColor(236, 72, 153);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.text('FROM', 20, y);
  y += 6;
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text(invoice.from.name || 'Your Name', 20, y);
  y += 5;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(invoice.from.email, 20, y);
  y += 4;
  doc.text(invoice.from.phone, 20, y);
  y += 4;
  doc.text(invoice.from.address, 20, y);
  // Fold seller compliance lines into the running y so the To block (and the
  // items table) push down past them — single-column layout, so the trailing
  // block must clear a 3-4-line seller detail block with no overlap.
  const sellerEnd = drawPartyDetails(doc, sellerDetailLines(invoice), 20, y);
  y = Math.max(y + 14, sellerEnd + 4);

  // To section
  doc.setTextColor(236, 72, 153);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.text('BILLED TO', 20, y);
  y += 6;
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text(invoice.to.name || 'Client Name', 20, y);
  y += 5;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(invoice.to.email, 20, y);
  y += 4;
  doc.text(invoice.to.phone, 20, y);
  y += 4;
  doc.text(invoice.to.address, 20, y);
  const buyerEnd = drawPartyDetails(doc, buyerDetailLines(invoice), 20, y);
  y = Math.max(y + 12, buyerEnd + 4);

  autoTable(doc, {
    startY: y,
    head: [['Description', 'Qty', 'Rate', 'Amount']],
    body: invoice.items.map((item) => [
      item.description,
      String(item.quantity),
      formatCurrencyPdf(item.rate, invoice.currency),
      formatCurrencyPdf(item.quantity * item.rate, invoice.currency),
    ]),
    theme: 'plain',
    headStyles: { textColor: [15, 23, 42], fontSize: 9, fontStyle: 'bold', lineColor: [236, 72, 153], lineWidth: 0.5 },
    styles: { fontSize: 10, textColor: [15, 23, 42], lineColor: [241, 245, 249], lineWidth: 0.2 },
    columnStyles: { 0: { cellWidth: 95 } },
    foot: totalsFoot(invoice, totals, 4),
    footStyles: { fontStyle: 'bold', textColor: [236, 72, 153] },
  });

  const finalY = (doc as any).lastAutoTable?.finalY || 180;
  const taxY = drawTaxAnnotation(doc, invoice, finalY, 20);
  if (invoice.notes) {
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);
    doc.text(`Notes: ${invoice.notes}`, 20, taxY + 14);
  }
  if (invoice.terms) {
    doc.text(`Terms: ${invoice.terms}`, 20, taxY + 22);
  }
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text('Generated by Billify', 20, 290);
}

// ─── Agency Template (Team) ─────────────────────────────────
// Dark header, white card body, full-width design
function generateAgency(doc: jsPDF, invoice: Invoice) {
  const totals = calculateTotals(invoice.items, invoice.taxRate);
  // Dark header band
  doc.setFillColor(17, 24, 39); // slate-900
  doc.rect(0, 0, 210, 50, 'F');

  // Brand in header
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text(invoice.from.name || 'Your Agency', 15, 25);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(148, 163, 184);
  doc.text(invoice.from.email, 15, 33);
  doc.text(invoice.from.phone, 15, 38);
  doc.text(invoice.from.address, 15, 43);

  // Big "INVOICE" on right
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(32);
  doc.setFont('helvetica', 'bold');
  doc.text('INVOICE', 195, 30, { align: 'right' });
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(148, 163, 184);
  doc.text(`#${invoice.number}`, 195, 38, { align: 'right' });

  // Yellow accent under header
  doc.setFillColor(250, 204, 21); // yellow-400
  doc.rect(0, 50, 210, 2, 'F');

  // Date row
  let y = 65;
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('Date', 15, y);
  doc.text('Due Date', 80, y);
  doc.text('Invoice #', 145, y);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);
  doc.text(invoice.date, 15, y + 5);
  doc.text(invoice.dueDate, 80, y + 5);
  doc.text(invoice.number, 145, y + 5);
  y += 18;

  // Bill To block
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.text('BILL TO', 15, y);
  y += 6;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(invoice.to.name || 'Client Name', 15, y);
  y += 5;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(invoice.to.email, 15, y);
  y += 4;
  doc.text(invoice.to.phone, 15, y);
  y += 4;
  doc.text(invoice.to.address, 15, y);
  // Seller info sits in the dark header band where gray compliance text would be
  // illegible, so seller + buyer details render together in the body above table.
  const detailsY = drawDetailsCombined(doc, invoice, 15, y);
  y = Math.max(y + 12, detailsY + 5);

  autoTable(doc, {
    startY: y,
    head: [['Description', 'Qty', 'Rate', 'Amount']],
    body: invoice.items.map((item) => [
      item.description,
      String(item.quantity),
      formatCurrencyPdf(item.rate, invoice.currency),
      formatCurrencyPdf(item.quantity * item.rate, invoice.currency),
    ]),
    theme: 'grid',
    headStyles: { fillColor: [17, 24, 39], textColor: 255, fontSize: 9, fontStyle: 'bold' },
    styles: { fontSize: 9, textColor: [15, 23, 42] },
    alternateRowStyles: { fillColor: [241, 245, 249] },
    foot: totalsFoot(invoice, totals, 4),
    footStyles: { fillColor: [250, 204, 21], textColor: [17, 24, 39], fontStyle: 'bold' },
  });

  const finalY = (doc as any).lastAutoTable?.finalY || 180;
  const taxY = drawTaxAnnotation(doc, invoice, finalY, 15);
  if (invoice.notes) {
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);
    doc.text(`Notes: ${invoice.notes}`, 15, taxY + 14);
  }
  doc.setFontSize(7);
  doc.setTextColor(148, 163, 184);
  doc.text(FOOTER_WITH_HOST, 15, 290);
}

// ─── Consulting Template (Team) ─────────────────────────────
// Minimalist formal, mono accents
function generateConsulting(doc: jsPDF, invoice: Invoice) {
  const totals = calculateTotals(invoice.items, invoice.taxRate);
  // Header with mono-style thin borders
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(14);
  doc.setFont('courier', 'bold');
  doc.text('INVOICE', 15, 22);

  doc.setFont('courier', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);
  doc.text(`No: ${invoice.number}`, 15, 30);
  doc.text(`Date: ${invoice.date}`, 15, 35);
  doc.text(`Due:  ${invoice.dueDate}`, 15, 40);

  // Right: company block in monospace
  doc.setFontSize(9);
  doc.text(invoice.from.name || 'Your Company', 195, 22, { align: 'right' });
  doc.setFontSize(7);
  doc.setTextColor(100, 116, 139);
  doc.text(invoice.from.email, 195, 27, { align: 'right' });
  doc.text(invoice.from.phone, 195, 31, { align: 'right' });
  doc.text(invoice.from.address, 195, 35, { align: 'right' });

  // Thin border around header
  doc.setDrawColor(15, 23, 42);
  doc.setLineWidth(0.3);
  doc.rect(15, 45, 180, 2, 'F');

  // Bill To
  let y = 58;
  doc.setFont('courier', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(15, 23, 42);
  doc.text('TO:', 15, y);
  doc.setFont('courier', 'normal');
  doc.setFontSize(10);
  doc.text(invoice.to.name || 'Client Name', 30, y);
  y += 5;
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text(invoice.to.email, 30, y);
  y += 4;
  doc.text(invoice.to.address, 30, y);
  y += 4;
  doc.text(invoice.to.phone, 30, y);
  // Seller block is a compact right-aligned header with no room for detail
  // lines, so seller + buyer compliance details render together above the table.
  const detailsY = drawDetailsCombined(doc, invoice, 15, y);
  y = Math.max(y + 12, detailsY + 5);

  autoTable(doc, {
    startY: y,
    head: [['DESCRIPTION', 'QTY', 'RATE', 'AMOUNT']],
    body: invoice.items.map((item) => [
      item.description,
      String(item.quantity),
      formatCurrencyPdf(item.rate, invoice.currency),
      formatCurrencyPdf(item.quantity * item.rate, invoice.currency),
    ]),
    theme: 'plain',
    headStyles: {
      font: 'courier',
      fontStyle: 'bold',
      textColor: [15, 23, 42],
      lineColor: [15, 23, 42],
      lineWidth: 0.3,
      fontSize: 9,
    },
    styles: { font: 'courier', fontSize: 9, textColor: [15, 23, 42], lineColor: [241, 245, 249], lineWidth: 0.1 },
    foot: totalsFoot(invoice, totals, 4, { subtotal: 'SUBTOTAL', tax: 'TAX', total: 'TOTAL' }),
    footStyles: { font: 'courier', fontStyle: 'bold', textColor: [15, 23, 42], lineColor: [15, 23, 42], lineWidth: 0.3 },
  });

  const finalY = (doc as any).lastAutoTable?.finalY || 180;
  const taxY = drawTaxAnnotation(doc, invoice, finalY, 15);
  if (invoice.notes) {
    doc.setFont('courier', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text(`Notes: ${invoice.notes}`, 15, taxY + 14);
  }
  if (invoice.terms) {
    doc.text(`Terms: ${invoice.terms}`, 15, taxY + 22);
  }
  doc.setFontSize(7);
  doc.setTextColor(148, 163, 184);
  doc.text('Generated by Billify', 15, 290);
}

// ─── Creative Template (Team) ───────────────────────────────
// Bright accent stripe, big number, art-direction style
function generateCreative(doc: jsPDF, invoice: Invoice) {
  const totals = calculateTotals(invoice.items, invoice.taxRate);
  // Big number on the left
  doc.setTextColor(245, 158, 11); // amber-500
  doc.setFontSize(90);
  doc.setFont('helvetica', 'bold');
  doc.text(`#${invoice.number}`, 15, 60);

  // Right side: invoice meta
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('INVOICE', 195, 30, { align: 'right' });
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(invoice.date, 195, 37, { align: 'right' });
  doc.text(`Due: ${invoice.dueDate}`, 195, 42, { align: 'right' });

  // Brand under big number
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(invoice.from.name || 'Your Studio', 15, 75);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(invoice.from.email, 15, 80);
  doc.text(invoice.from.phone, 15, 84);
  doc.text(invoice.from.address, 15, 88);

  // Accent line
  doc.setFillColor(245, 158, 11);
  doc.rect(15, 95, 60, 3, 'F');

  // Bill To
  let y = 108;
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.text('FOR', 15, y);
  doc.setFontSize(12);
  doc.text(invoice.to.name || 'Client Name', 15, y + 7);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text(invoice.to.email, 15, y + 13);
  doc.text(invoice.to.address, 15, y + 18);
  doc.text(invoice.to.phone, 15, y + 23);
  // Seller block is an art element (big-number region + accent stripe) with no
  // room for detail lines, so seller + buyer details render together above table.
  const detailsY = drawDetailsCombined(doc, invoice, 15, y + 23);
  y = Math.max(y + 32, detailsY + 5);

  autoTable(doc, {
    startY: y,
    head: [['Item', 'Qty', 'Rate', 'Amount']],
    body: invoice.items.map((item) => [
      item.description,
      String(item.quantity),
      formatCurrencyPdf(item.rate, invoice.currency),
      formatCurrencyPdf(item.quantity * item.rate, invoice.currency),
    ]),
    theme: 'plain',
    headStyles: { fontStyle: 'bold', textColor: [15, 23, 42], lineColor: [15, 23, 42], lineWidth: 0.5 },
    styles: { fontSize: 10, textColor: [15, 23, 42] },
    foot: totalsFoot(invoice, totals, 4),
    footStyles: { fontStyle: 'bold', fontSize: 12, textColor: [245, 158, 11] },
  });

  const finalY = (doc as any).lastAutoTable?.finalY || 180;
  const taxY = drawTaxAnnotation(doc, invoice, finalY, 15);
  if (invoice.notes) {
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);
    doc.text(invoice.notes, 15, taxY + 14);
  }
  doc.setFontSize(7);
  doc.setTextColor(148, 163, 184);
  doc.text('Generated by Billify', 15, 290);
}

// Subtotal / tax / total are derived once per renderer via calculateTotals
// (imported from @/types) so the totalling logic has a single source of truth
// shared with the editor's live preview, instead of being re-rolled here.
