'use client';

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Invoice, formatCurrency } from '@/types';

export function generatePDF(invoice: Invoice): Blob {
  const doc = new jsPDF();

  // Sanitize all text fields to prevent jsPDF injection from HTML tags
  const clean = (s: string) => s.replace(/<[^\u003e]*>/g, '');
  const safeInvoice: Invoice = {
    ...invoice,
    number: clean(invoice.number),
    from: {
      ...invoice.from,
      name: clean(invoice.from.name),
      email: clean(invoice.from.email),
      phone: clean(invoice.from.phone),
      address: clean(invoice.from.address),
    },
    to: {
      ...invoice.to,
      name: clean(invoice.to.name),
      email: clean(invoice.to.email),
      phone: clean(invoice.to.phone),
      address: clean(invoice.to.address),
    },
    items: invoice.items.map(item => ({
      ...item,
      description: clean(item.description),
    })),
    notes: clean(invoice.notes),
    terms: clean(invoice.terms),
  };

  if (safeInvoice.template === 'modern') {
    generateModern(doc, safeInvoice);
  } else if (safeInvoice.template === 'classic') {
    generateClassic(doc, safeInvoice);
  } else if (safeInvoice.template === 'minimal') {
    generateMinimal(doc, safeInvoice);
  } else if (safeInvoice.template === 'clean') {
    generateClean(doc, safeInvoice);
  } else if (safeInvoice.template === 'bold') {
    generateBold(doc, safeInvoice);
  } else {
    generateExecutive(doc, safeInvoice);
  }

  return doc.output('blob');
}

function generateModern(doc: jsPDF, invoice: Invoice) {
  // Header gradient-ish band
  doc.setFillColor(59, 130, 246);
  doc.rect(0, 0, 210, 40, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('INVOICE', 15, 25);

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`#${invoice.number}`, 15, 32);

  doc.setFontSize(10);
  doc.text(`Date: ${invoice.date}`, 160, 20);
  doc.text(`Due: ${invoice.dueDate}`, 160, 26);

  // From / To
  let y = 55;
  doc.setTextColor(31, 41, 55);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('From:', 15, y);
  if (invoice.from.logo) {
    try { doc.addImage(invoice.from.logo, 'JPEG', 15, y + 2, 20, 20); } catch {}
  }
  doc.setFont('helvetica', 'normal');
  doc.text(invoice.from.name || 'Your Company', 15, y + 10);
  doc.text(invoice.from.email, 15, y + 15);
  doc.text(invoice.from.phone, 15, y + 20);
  doc.text(invoice.from.address, 15, y + 25);

  doc.setFont('helvetica', 'bold');
  doc.text('Bill To:', 110, y);
  doc.setFont('helvetica', 'normal');
  doc.text(invoice.to.name || 'Client Name', 110, y + 10);
  doc.text(invoice.to.email, 110, y + 15);
  doc.text(invoice.to.phone, 110, y + 20);
  doc.text(invoice.to.address, 110, y + 25);

  // Items table
  autoTable(doc, {
    startY: y + 35,
    head: [['Description', 'Qty', 'Rate', 'Amount']],
    body: invoice.items.map((item) => [
      item.description,
      String(item.quantity),
      formatCurrency(item.rate, invoice.currency),
      formatCurrency(item.quantity * item.rate, invoice.currency),
    ]),
    theme: 'striped',
    headStyles: { fillColor: [59, 130, 246], textColor: 255 },
    styles: { fontSize: 11 },
    foot: [
      ['', '', 'Subtotal', formatCurrency(subtotal(invoice), invoice.currency)],
      ['', '', `Tax (${invoice.taxRate}%)`, formatCurrency(taxAmount(invoice), invoice.currency)],
      ['', '', 'Total', formatCurrency(total(invoice), invoice.currency)],
    ],
    footStyles: { fillColor: [243, 244, 246], textColor: [31, 41, 55], fontStyle: 'bold' },
  });

  const finalY = (doc as any).lastAutoTable?.finalY || 180;
  if (invoice.notes) {
    doc.text('Notes:', 15, finalY + 15);
    doc.setFontSize(10);
    doc.text(invoice.notes, 15, finalY + 22);
  }
  if (invoice.terms) {
    doc.text(`Terms: ${invoice.terms}`, 15, finalY + 35);
  }

  doc.setFontSize(9);
  doc.setTextColor(156, 163, 175);
  doc.text('Generated by Billify', 15, 290);
}

function generateClassic(doc: jsPDF, invoice: Invoice) {
  doc.setTextColor(17, 24, 39);
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.text('INVOICE', 15, 25);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(`#${invoice.number}`, 15, 33);
  doc.text(`Date: ${invoice.date}`, 140, 25);
  doc.text(`Due: ${invoice.dueDate}`, 140, 32);

  doc.setDrawColor(200, 200, 200);
  doc.line(15, 40, 195, 40);

  let y = 55;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('From', 15, y);
  doc.text('Bill To', 110, y);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  if (invoice.from.logo) {
    try { doc.addImage(invoice.from.logo, 'JPEG', 15, y + 2, 18, 18); } catch {}
  }
  doc.text(invoice.from.name || 'Your Company', 15, y + 10);
  doc.text(invoice.from.email, 15, y + 15);
  doc.text(invoice.from.phone, 15, y + 20);
  doc.text(invoice.from.address, 15, y + 25);

  doc.text(invoice.to.name || 'Client Name', 110, y + 10);
  doc.text(invoice.to.email, 110, y + 15);
  doc.text(invoice.to.phone, 110, y + 20);
  doc.text(invoice.to.address, 110, y + 25);

  autoTable(doc, {
    startY: y + 35,
    head: [['Item', 'Description', 'Qty', 'Rate', 'Amount']],
    body: invoice.items.map((item, i) => [
      String(i + 1),
      item.description,
      String(item.quantity),
      formatCurrency(item.rate, invoice.currency),
      formatCurrency(item.quantity * item.rate, invoice.currency),
    ]),
    theme: 'grid',
    headStyles: { fillColor: [31, 41, 55], textColor: 255 },
    styles: { fontSize: 11 },
    foot: [
      ['', '', '', 'Subtotal', formatCurrency(subtotal(invoice), invoice.currency)],
      ['', '', '', `Tax (${invoice.taxRate}%)`, formatCurrency(taxAmount(invoice), invoice.currency)],
      ['', '', '', 'Total', formatCurrency(total(invoice), invoice.currency)],
    ],
  });

  const finalY = (doc as any).lastAutoTable?.finalY || 180;
  if (invoice.notes) {
    doc.setFontSize(10);
    doc.text(`Notes: ${invoice.notes}`, 15, finalY + 15);
  }
  doc.setFontSize(9);
  doc.text('Generated by Billify', 15, 290);
}

function generateMinimal(doc: jsPDF, invoice: Invoice) {
  doc.setTextColor(31, 41, 55);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'normal');
  doc.text('Invoice', 15, 25);

  doc.setFontSize(10);
  doc.text(`#${invoice.number}  ·  ${invoice.date}  ·  Due ${invoice.dueDate}`, 15, 33);

  let y = 55;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('FROM', 15, y);
  doc.text('TO', 110, y);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  if (invoice.from.logo) {
    try { doc.addImage(invoice.from.logo, 'JPEG', 15, y + 3, 16, 16); } catch {}
  }
  doc.text(invoice.from.name || 'Your Company', 15, y + 12);
  doc.text(invoice.from.email, 15, y + 17);
  doc.text(invoice.from.phone, 15, y + 22);
  doc.text(invoice.from.address, 15, y + 27);

  doc.text(invoice.to.name || 'Client Name', 110, y + 12);
  doc.text(invoice.to.email, 110, y + 17);
  doc.text(invoice.to.phone, 110, y + 22);
  doc.text(invoice.to.address, 110, y + 27);

  autoTable(doc, {
    startY: y + 38,
    head: [['Description', 'Qty', 'Rate', 'Amount']],
    body: invoice.items.map((item) => [
      item.description,
      String(item.quantity),
      formatCurrency(item.rate, invoice.currency),
      formatCurrency(item.quantity * item.rate, invoice.currency),
    ]),
    theme: 'plain',
    headStyles: { fontStyle: 'bold', textColor: [31, 41, 55] },
    styles: { fontSize: 10, lineColor: [200, 200, 200], lineWidth: 0.1 },
    foot: [
      ['', '', 'Subtotal', formatCurrency(subtotal(invoice), invoice.currency)],
      ['', '', `Tax (${invoice.taxRate}%)`, formatCurrency(taxAmount(invoice), invoice.currency)],
      ['', '', 'Total', formatCurrency(total(invoice), invoice.currency)],
    ],
    footStyles: { fontStyle: 'bold', textColor: [31, 41, 55] },
  });

  const finalY = (doc as any).lastAutoTable?.finalY || 180;
  if (invoice.notes) {
    doc.setFontSize(10);
    doc.text(`Notes: ${invoice.notes}`, 15, finalY + 14);
  }
  doc.setFontSize(9);
  doc.text('Generated by Billify', 15, 290);
}

// ─── Clean Template ────────────────────────────────────
// White space, subtle borders, refined typography
function generateClean(doc: jsPDF, invoice: Invoice) {
  doc.setTextColor(51, 65, 85);
  doc.setFontSize(26);
  doc.setFont('helvetica', 'normal');
  doc.text('Invoice', 15, 28);

  doc.setFontSize(9);
  doc.text(`#${invoice.number}`, 15, 36);

  doc.setTextColor(100, 116, 139);
  doc.text(`Date: ${invoice.date}`, 160, 28);
  doc.text(`Due: ${invoice.dueDate}`, 160, 34);

  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.3);
  doc.line(15, 45, 195, 45);

  let y = 58;
  doc.setTextColor(51, 65, 85);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Billed From', 15, y);
  doc.text('Billed To', 110, y);

  doc.setFont('helvetica', 'normal');
  if (invoice.from.logo) {
    try { doc.addImage(invoice.from.logo, 'JPEG', 15, y + 3, 18, 18); } catch {}
  }
  doc.text(invoice.from.name || 'Your Company', 15, y + 11);
  doc.text(invoice.from.email, 15, y + 16);
  doc.text(invoice.from.phone, 15, y + 21);
  doc.text(invoice.from.address, 15, y + 26);

  doc.text(invoice.to.name || 'Client Name', 110, y + 11);
  doc.text(invoice.to.email, 110, y + 16);
  doc.text(invoice.to.phone, 110, y + 21);
  doc.text(invoice.to.address, 110, y + 26);

  autoTable(doc, {
    startY: y + 34,
    head: [['Description', 'Qty', 'Rate', 'Amount']],
    body: invoice.items.map((item) => [
      item.description,
      String(item.quantity),
      formatCurrency(item.rate, invoice.currency),
      formatCurrency(item.quantity * item.rate, invoice.currency),
    ]),
    theme: 'plain',
    headStyles: {
      fontStyle: 'bold',
      textColor: [51, 65, 85],
      lineColor: [203, 213, 225],
      lineWidth: 0.5,
    },
    styles: { fontSize: 10, lineColor: [226, 232, 240], lineWidth: 0.3 },
    foot: [
      ['', '', 'Subtotal', formatCurrency(subtotal(invoice), invoice.currency)],
      ['', '', `Tax (${invoice.taxRate}%)`, formatCurrency(taxAmount(invoice), invoice.currency)],
      ['', '', 'Total', formatCurrency(total(invoice), invoice.currency)],
    ],
    footStyles: { fontStyle: 'bold', textColor: [15, 23, 42] },
  });

  const finalY = (doc as any).lastAutoTable?.finalY || 180;
  if (invoice.notes) {
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text(`Notes: ${invoice.notes}`, 15, finalY + 14);
  }
  if (invoice.terms) {
    doc.text(`Terms: ${invoice.terms}`, 15, finalY + 22);
  }
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text('Generated by Billify', 15, 290);
}

// ─── Bold Template ────────────────────────────────────
// High contrast, large type, strong visual hierarchy
function generateBold(doc: jsPDF, invoice: Invoice) {
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, 210, 50, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(32);
  doc.setFont('helvetica', 'bold');
  doc.text('INVOICE', 15, 30);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(`#${invoice.number}`, 15, 40);
  doc.text(`Date: ${invoice.date}`, 140, 30);
  doc.text(`Due: ${invoice.dueDate}`, 140, 38);

  let y = 65;
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('FROM', 15, y);
  doc.text('TO', 110, y);

  doc.setFont('helvetica', 'normal');
  if (invoice.from.logo) {
    try { doc.addImage(invoice.from.logo, 'JPEG', 15, y + 3, 18, 18); } catch {}
  }
  doc.text(invoice.from.name || 'Your Company', 15, y + 11);
  doc.text(invoice.from.email, 15, y + 16);
  doc.text(invoice.from.phone, 15, y + 21);
  doc.text(invoice.from.address, 15, y + 26);

  doc.text(invoice.to.name || 'Client Name', 110, y + 11);
  doc.text(invoice.to.email, 110, y + 16);
  doc.text(invoice.to.phone, 110, y + 21);
  doc.text(invoice.to.address, 110, y + 26);

  autoTable(doc, {
    startY: y + 34,
    head: [['Description', 'Qty', 'Rate', 'Amount']],
    body: invoice.items.map((item) => [
      item.description,
      String(item.quantity),
      formatCurrency(item.rate, invoice.currency),
      formatCurrency(item.quantity * item.rate, invoice.currency),
    ]),
    theme: 'grid',
    headStyles: { fillColor: [15, 23, 42], textColor: 255, fontSize: 11 },
    styles: { fontSize: 11, textColor: [15, 23, 42] },
    foot: [
      ['', '', 'Subtotal', formatCurrency(subtotal(invoice), invoice.currency)],
      ['', '', `Tax (${invoice.taxRate}%)`, formatCurrency(taxAmount(invoice), invoice.currency)],
      ['', '', 'Total', formatCurrency(total(invoice), invoice.currency)],
    ],
    footStyles: { fillColor: [241, 245, 249], textColor: [15, 23, 42], fontStyle: 'bold', fontSize: 12 },
  });

  const finalY = (doc as any).lastAutoTable?.finalY || 180;
  if (invoice.notes) {
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text(`Notes: ${invoice.notes}`, 15, finalY + 14);
  }
  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184);
  doc.text('Generated by Billify', 15, 290);
}

// ─── Executive Template ────────────────────────────────────
// Formal, refined layout with accent lines and sophisticated typography
function generateExecutive(doc: jsPDF, invoice: Invoice) {
  // Subtle top accent line
  doc.setFillColor(180, 83, 9); // amber/teal accent
  doc.rect(0, 0, 210, 3, 'F');

  doc.setTextColor(51, 65, 85);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('TAX INVOICE', 15, 22);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`Invoice #: ${invoice.number}`, 15, 30);
  doc.text(`Date: ${invoice.date}`, 160, 22);
  doc.text(`Due Date: ${invoice.dueDate}`, 160, 28);

  doc.setDrawColor(180, 83, 9);
  doc.setLineWidth(0.4);
  doc.line(15, 36, 195, 36);

  let y = 48;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(100, 116, 139);
  doc.text('BILLED FROM', 15, y);
  doc.text('BILLED TO', 110, y);

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(51, 65, 85);
  if (invoice.from.logo) {
    try { doc.addImage(invoice.from.logo, 'JPEG', 15, y + 3, 16, 16); } catch {}
  }
  doc.text(invoice.from.name || 'Your Company', 15, y + 10);
  doc.text(invoice.from.email, 15, y + 15);
  doc.text(invoice.from.phone, 15, y + 20);
  doc.text(invoice.from.address, 15, y + 25);

  doc.text(invoice.to.name || 'Client Name', 110, y + 10);
  doc.text(invoice.to.email, 110, y + 15);
  doc.text(invoice.to.phone, 110, y + 20);
  doc.text(invoice.to.address, 110, y + 25);

  autoTable(doc, {
    startY: y + 32,
    head: [['Description', 'Qty', 'Rate', 'Amount']],
    body: invoice.items.map((item) => [
      item.description,
      String(item.quantity),
      formatCurrency(item.rate, invoice.currency),
      formatCurrency(item.quantity * item.rate, invoice.currency),
    ]),
    theme: 'striped',
    headStyles: {
      fillColor: [51, 65, 85],
      textColor: 255,
      fontSize: 10,
    },
    styles: { fontSize: 10, textColor: [51, 65, 85] },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    foot: [
      ['', '', 'Subtotal', formatCurrency(subtotal(invoice), invoice.currency)],
      ['', '', `Tax (${invoice.taxRate}%)`, formatCurrency(taxAmount(invoice), invoice.currency)],
      ['', '', 'Total', formatCurrency(total(invoice), invoice.currency)],
    ],
    footStyles: { fillColor: [241, 245, 249], textColor: [15, 23, 42], fontStyle: 'bold' },
  });

  const finalY = (doc as any).lastAutoTable?.finalY || 180;
  if (invoice.notes) {
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text(`Notes: ${invoice.notes}`, 15, finalY + 14);
  }
  if (invoice.terms) {
    doc.text(`Payment Terms: ${invoice.terms}`, 15, finalY + 22);
  }
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text('Generated by Billify — billify.me', 15, 290);
}

function subtotal(invoice: Invoice): number {
  return invoice.items.reduce((sum, item) => sum + item.quantity * item.rate, 0);
}

function taxAmount(invoice: Invoice): number {
  return subtotal(invoice) * (invoice.taxRate / 100);
}

function total(invoice: Invoice): number {
  return subtotal(invoice) + taxAmount(invoice);
}
